name: 32 Bit Linux

on:
  push:
    branches:
      - main
      - 2.0.x
  pull_request:
    branches:
      - main
      - 2.0.x
    paths-ignore:
      - "doc/**"

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-22.04
    container:
      image: quay.io/pypa/manylinux2014_i686
      options: --platform linux/386
    steps:
      - name: Checkout pandas Repo
        # actions/checkout does not work since it requires node
        run: |
          git config --global --add safe.directory $PWD

          if [ $GITHUB_EVENT_NAME != pull_request ]; then
              git clone --recursive --branch=$GITHUB_REF_NAME https://github.com/${GITHUB_REPOSITORY}.git $GITHUB_WORKSPACE
              git reset --hard $GITHUB_SHA
          else
              git clone --recursive https://github.com/${GITHUB_REPOSITORY}.git $GITHUB_WORKSPACE
              git fetch origin $GITHUB_REF:my_ref_name
              git checkout $GITHUB_BASE_REF
              git -c user.email="you@example.com" merge --no-commit my_ref_name
          fi
      - name: Build environment and Run Tests
        run: |
          /opt/python/cp38-cp38/bin/python -m venv ~/virtualenvs/pandas-dev
          . ~/virtualenvs/pandas-dev/bin/activate
          python -m pip install --no-cache-dir --no-deps -U pip wheel setuptools
          python -m pip install --no-cache-dir versioneer[toml] cython numpy python-dateutil pytz pytest>=7.0.0 pytest-xdist>=2.2.0 pytest-asyncio>=0.17 hypothesis>=6.46.1
          python setup.py build_ext -q -j$(nproc)
          python -m pip install --no-cache-dir --no-build-isolation --no-use-pep517 -e .
          python -m pip list
          export PANDAS_CI=1
          python -m pytest -m 'not slow and not network and not clipboard and not single_cpu' pandas --junitxml=test-data.xml
      # - name: Run 32-bit manylinux2014 Docker Build / Tests
      #   run: |
      #     # Without this (line 34), versioneer will not be able to determine the pandas version.
      #     # This is because of a security update to git that blocks it from reading the config folder if
      #     # it is not owned by the current user. We hit this since the "mounted" folder is not hit by the
      #     # Docker container.
      #     # xref https://github.com/pypa/manylinux/issues/1309
      #     docker pull quay.io/pypa/manylinux2014_i686
      #     docker run --platform linux/386 -v $(pwd):/pandas quay.io/pypa/manylinux2014_i686 \
      #     /bin/bash -xc "cd pandas && \
      #     git config --global --add safe.directory /pandas && \
      #     /opt/python/cp38-cp38/bin/python -m venv ~/virtualenvs/pandas-dev && \
      #     . ~/virtualenvs/pandas-dev/bin/activate && \
      #     python -m pip install --no-deps -U pip wheel 'setuptools<60.0.0' && \
      #     python -m pip install versioneer[toml] && \
      #     python -m pip install cython numpy python-dateutil pytz pytest>=7.0.0 pytest-xdist>=2.2.0 pytest-asyncio>=0.17 hypothesis>=6.46.1 && \
      #     python setup.py build_ext -q -j$(nproc) && \
      #     python -m pip install --no-build-isolation --no-use-pep517 -e . && \
      #     python -m pip list && \
      #     export PANDAS_CI=1 && \
      #     pytest -m 'not slow and not network and not clipboard and not single_cpu' pandas --junitxml=test-data.xml"
    concurrency:
      # https://github.community/t/concurrecy-not-work-for-push/183068/7
      group: ${{ github.event_name == 'push' && github.run_number || github.ref }}-32bit
      cancel-in-progress: true
